Fixing symmetry for right wings
mdolab/OpenAeroStruct pull request #381
Opened 2022-03-14 22:05 UTC by timryanb

## Purpose
This PR addresses #244. Symmetric wings can now be used with the aerodynamics solver if they lie in the right side of the symmetry plane. Prior to this, OAS only gave correct results for left wings.

## Expected time until merged
a week

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing
This fix can be tested by taking a standard left wing model and flipping the y nodes a shown below:
```
# Flip left wing to lie on right of symmetry plane
mesh[:, :ny, :] = inputs[mesh_name]
mesh[:, ny+1:, :] = inputs[mesh_name][:, ::-1, :]
mesh[:, ny+1:, 1] *= -1.
```

The new flipped surface can be passed to the aerodynamic component and _should_ give a consistent solution to a left wing or full wing model.

## Checklist

- [x] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [x] I have run unit and regression tests which pass locally with my changes
- [x] I have added new tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation

2022-03-15 22:01 UTC, kanekosh requested changes
Thank you @timryanb! I added a few comments on the new regression tests.

2022-04-04 19:17 UTC, timryanb commented on openaerostruct/tests/test_simple_rect_right_aero.py
> +        assert_near_equal(prob["aero_point_0.wing_perf.CD"][0], 0.03487336411850356, 1e-6)
Should be addressed now

2022-04-04 19:17 UTC, timryanb commented on openaerostruct/tests/test_aero_ground_effect_right.py
> +        assert_near_equal(prob["aero_point_0.wing_perf.CD"][0], 0.033389699871650073, 1e-6)
Should be addressed now

2022-04-04 21:56 UTC, kanekosh approved these changes
Thank you @timryanb! I'll merge this PR after fixing `black` in a separate PR - they recently broke a thrid-party dependency and we need to version up `black` to fix that.

2022-04-06 16:12 UTC, nwu63 commented
Maybe we also want to bump the version and make a new release?

2022-04-06 18:01 UTC, kanekosh approved these changes

2022-04-06 18:01 UTC, merged